### Variables
# @baseUrl = http://localhost:8080
@baseUrl = https://cloudrun-goexpert-weather-59578092225.us-central1.run.app
### Get Temperature
GET {{baseUrl}}/temperature/35780000
Content-Type: application/json

### Get Temperature - invalid CEP
GET {{baseUrl}}/temperature/35780 00
Content-Type: application/json

### Get Temperature - invalid CEP correct format
GET {{baseUrl}}/temperature/35780300
Content-Type: application/json
